
import Navbar from "../components/navbar/Navbar"
import "./home.scss"


 const Home = () => {
  return (
         <div className='home'>
            <Navbar />
            <img width= "100%" src="https://media.gqmagazine.fr/photos/5d8b6763c7191e00083ebdb9/2:3/w_712,h_1068,c_limit/reussite.jpg" alt="Photo_Profil" 
            
            />
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore dolores necessitatibus dolorum accusamus voluptates! Assumenda, itaque atque nam autem ullam illum distinctio numquam excepturi ipsam earum, similique repellendus ducimus animi ab saepe aspernatur ad voluptate ex adipisci delectus deleniti facilis. Exercitationem eos a cupiditate ducimus nesciunt ea id labore illo.
        </div>

  )
}

export default Home